/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author danielalvarado
 */
public class checkListDialog extends javax.swing.JDialog {
    public JTextField[] textEditsArray;
    public JLabel[] labelsArray;
    public JButton[] buttonsArray;
    
    
    /**
     * Creates new form checkListDialog
     */
    public checkListDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        createGrid(6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(502, 292));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jLabel1.setText("TEXTO O ACCION");

        jLabel2.setText("RESULTADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(276, 276, 276)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkListDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkListDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkListDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkListDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                checkListDialog dialog = new checkListDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
        //action 
    Action action = new AbstractAction()
    {
    @Override
    public void actionPerformed(ActionEvent e){
        //GetUserDialog.setVisible(true);
        }
    };
    
    private void createGrid(int _nItems) {
        this.textEditsArray = new JTextField[_nItems];
        this.labelsArray = new JLabel[_nItems];
        this.buttonsArray = new JButton[_nItems];
        
        GridBagConstraints gridBagConstraintsL,gridBagConstraintsT,gridBagConstraintsB;
        for (int i =0; i < _nItems; i ++ ) {
            this.textEditsArray[i] = new javax.swing.JTextField();
            this.textEditsArray[i].setText(Integer.toString(i));
            this.labelsArray[i] = new javax.swing.JLabel();
            this.labelsArray[i].setText("Label"+i);
            this.buttonsArray[i] = new JButton("Aceptar");
            
            gridBagConstraintsL = createBagCons(i,1);
            gridBagConstraintsT = createBagCons(i,2);
            gridBagConstraintsB = createBagCons(i,3);
            

            jScrollPane1.add(this.labelsArray[i], gridBagConstraintsL);
            jScrollPane1.add(this.textEditsArray[i], gridBagConstraintsT);
            jScrollPane1.add(this.textEditsArray[i], gridBagConstraintsB);
            
            
            //this.textEditsArray[i].addActionListener(action);
            
        }
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
        
    }

    
    
    private GridBagConstraints createBagCons(int _pos,int _label) {
        GridBagConstraints gridBagConstraintsL = new java.awt.GridBagConstraints();
            gridBagConstraintsL.gridx = _label;
            gridBagConstraintsL.gridy = _pos;
            gridBagConstraintsL.ipadx = 39;
            gridBagConstraintsL.ipady = 13;
            gridBagConstraintsL.weightx = 1;
            gridBagConstraintsL.weighty = 1;
            gridBagConstraintsL.fill = GridBagConstraints.BOTH;
            //gridBagConstraintsL.anchor = java.awt.GridBagConstraints.NORTHWEST;
            gridBagConstraintsL.insets = new java.awt.Insets(6, 6, 0, 0);
        return gridBagConstraintsL;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
